language: generic
os: linux
dist: xenial

before_install:
  - sudo apt-get update
  - sudo apt-get install libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libglew-dev ninja-build
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.16.0-rc2/cmake-3.16.0-rc2-Linux-x86_64.tar.gz
  - tar -xvf cmake-3.16.0-rc2-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.16.0-rc2-Linux-x86_64 cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - cd ${TRAVIS_BUILD_DIR}

matrix:
  include:
  - compiler: gcc
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-9']
    env:
      - CXX=g++-9

  - compiler: clang
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-8']
        packages: ['clang-8']
    env:
      - CXX=clang++-8

before_script: 
  - mkdir build && cd build
  - cmake -GNinja ..

script:
  - ninja -j4
 