version: 1.0.{build}
image: Visual Studio 2019

configuration:
  - Release

# cache:
#   - build\cmake-3.16.0-rc2-win64-x64 -> appveyor.yml

before_build:
  # Clone libs
  - cmd: git submodule update --init --recursive
  - cmd: if not exist build mkdir build
  - cmd: cd build
  # Download latest CMake
  - ps: Start-FileDownload 'https://github.com/Kitware/CMake/releases/download/v3.16.0-rc2/cmake-3.16.0-rc2-win64-x64.zip' 'cmake.zip'
  # Extract it in build folder
  - cmd: 7z x cmake.zip
  # Generate solution
  - cmd: .\cmake-3.16.0-rc2-win64-x64\bin\cmake.exe ..

build:
  project: build\Hazel.sln
  parallel: true
  verbosity: minimal
